-- ============================================
-- PHP Language Server (Intelephense)
-- ============================================

return {
    settings = {
        intelephense = {
            environment = {
                documentRoot = ".",
                includePaths = { "." },
            },
            format = {
                enable = true,
                indentSpaces = 4,
                indentFinalNewline = true,
                insertSpaces = true,
                maxBindingIndentationDepth = 10,
                braceOnNewLine = false,
                lineLength = 120,
            },
            files = {
                maxSize = 1000000,
                exclude = { "**/.git", "**/.svn", "**/.hg", "**/CVS", "**/.DS_Store", "**/node_modules" },
            },
            completion = {
                insertUseDeclaration = true,
                fullyQualifyGlobalConstants = false,
                fullyQualifyGlobalFunctions = false,
                fullyQualifyGlobalClasses = false,
            },
            diagnostics = {
                enable = true,
                run = "onSave",
                onSave = true,
                onType = false,
                suppressDeprecated = true,
            },
            stubs = {
                "aerospike",
                "amqp",
                "apcu",
                "ast",
                "bcmath",
                "bz2",
                "calendar",
                "cmark",
                "com_dotnet",
                "couchbase",
                "crypto",
                "ctype",
                "curl",
                "date",
                "dba",
                "dbus",
                "decimal",
                "dom",
                "ds",
                "eio",
                "enchant",
                "ev",
                "event",
                "exif",
                "ffi",
                "file",
                "fileinfo",
                "filter",
                "ftp",
                "gd",
                "gearman",
                "gender",
                "gettext",
                "gmp",
                "grpc",
                "hash",
                "http",
                "ibm_db2",
                "iconv",
                "igbinary",
                "imap",
                "inotify",
                "intl",
                "json",
                "judy",
                "ldap",
                "libxml",
                "lua",
                "luasandbox",
                "mailparse",
                "mbstring",
                "mcrypt",
                "memcache",
                "memcached",
                "meta",
                "mhash",
                "mime_type",
                "mongodb",
                "msgpack",
                "mysql",
                "mysqli",
                "mysqlnd",
                "native",
                "oci8",
                "odbc",
                "openssl",
                "parallel",
                "parsekit",
                "pcntl",
                "pcre",
                "pdo",
                "pgsql",
                "phar",
                "phpdbg",
                "posix",
                "pspell",
                "psr",
                "pthreads",
                "radius",
                "rar",
                "rdkafka",
                "readline",
                "recode",
                "redis",
                "reflection",
                "regex",
                "resources",
                "rpmreader",
                "rrd",
                "runkit7",
                "sapi",
                "seaslog",
                "sem",
                "shmop",
                "simdjson",
                "simplexml",
                "snmp",
                "soap",
                "sockets",
                "sodium",
                "solr",
                "sort",
                "soundex",
                "spl",
                "spl_types",
                "sqlite3",
                "sqlsrv",
                "ssh2",
                "ssl",
                "standard",
                "stomp",
                "stream",
                "string",
                "striped_files",
                "strnatcmp",
                "strptime",
                "strrev",
                "strtok",
                "strtr",
                "suhosin",
                "svm",
                "svn",
                "syslog",
                "system",
                "sysvmsg",
                "sysvsem",
                "sysvshm",
                "taint",
                "tidy",
                "tokenizer",
                "uapprover",
                "uconvert",
                "udis86",
                "ufilesystem",
                "uid",
                "unirule",
                "unistring",
                "uopz",
                "uparcel",
                "urandom",
                "uri",
                "uriparser",
                "user_defined_functions",
                "usleep",
                "uuid",
                "var",
                "var_export",
                "varnish",
                "vips",
                "weak_references",
                "wincache",
                "winbinder",
                "windows_error",
                "wincrypt",
                "winreg",
                "winsock",
                "winspool",
                "wordwrap",
                "xcache",
                "xdebug",
                "xdiff",
                "xml",
                "xmlrpc",
                "xmlwriter",
                "xrange",
                "xsl",
                "xunit",
                "yac",
                "yaf",
                "yar",
                "yaml",
                "yaz",
                "yconf",
                "zip",
                "zlib",
                "zmq",
            },
        },
    },
}
